site_name: SCSS Documentation
site_url: https://ramyromel.github.io/SCSS/
repo_url: https://github.com/Ramyromel/SCSS
repo_name: SCSS

docs_dir: docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Whitepaper: whitepaper.md
  - Testing: testing.md
  - Philosophy: philosophy.md
  - License: license.md
